FROM node:8-slim

## PART 1: System components
## =======================
# Install utilities
RUN apt-get update --fix-missing && apt-get -y upgrade &&\
apt-get install -y sudo curl wget unzip git

# Install yarn
#RUN npm --global install yarn


## PART 2: Express components
## =======================
#RUN npm install express --save \
#    && npm install body-parser --save \
#    && npm install cookie-parser --save \
#    && npm install multer --save
